# Generated by Django 4.1.3 on 2023-07-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(max_length=500)),
                ('DOB', models.CharField(max_length=500)),
                ('dates', models.CharField(max_length=500)),
                ('urls', models.URLField()),
            ],
        ),
    ]
